include(cc_test)

cc_test(
  NAME
    npu_deepseek_v4_indexer_test
  SRCS
    deepseek_v4_indexer_tests.cpp
  DEPS
    :npu_torch_layers
    :state_dict
    :xllm_ops
    glog::glog
    torch
    GTest::gtest_main
)

target_link_libraries(npu_deepseek_v4_indexer_test
                      PRIVATE
                      ascendcl
                      hccl
                      c_sec
                      nnopbase
                      atb)

target_link_options(npu_deepseek_v4_indexer_test PRIVATE
  "-Wl,--whole-archive"
  "${CMAKE_BINARY_DIR}/third_party/spdlog/libspdlog.a"
  "-Wl,--no-whole-archive")
